AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Nodejs lambda
Resources:
 NodeFunction:
  Type: AWS::Serverless::Function
  Properties:
   Handler: index.handler
   Runtime: nodejs6.1
   CodeUri: ./
   Events:
    MyNodeApi:
     Type: Api
     Properties:
      Path: /nodeResource
      Method: GET
